name: Deploy

on:
  push:
  workflow_dispatch:
    inputs:
      from_scratch:
        description: Enter 'skip' to create a new database from scratch
      build_plugin_directory_extras:
        description: Extra command-line options to pass to build_plugin_directory

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
    - name: Download previous database
      if: github.event.inputs.from_scratch != 'skip'
      run: |
        curl -O https://datasette.io/content.db
    - name: Fetch plugins data
      run: |
        eval "python build_plugin_directory.py content.db --fetch-missing-releases $build_plugin_directory_extras --extra-repo dogsheep/dogsheep-beta"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        build_plugin_directory_extras: ${{ github.event.inputs.build_plugin_directory_extras }}
    - name: Populate news database
      run: |
        sqlite-utils content.db 'drop table if exists news'
        yaml-to-sqlite content.db news news.yaml
    - name: Fetch documentation database for search index
      run: curl -o docs-index.db https://latest-docs.datasette.io/docs.db
    - name: Fetch my relevant blog content
      run: python fetch_blog_content.py blog.db datasette dogsheep sqliteutils
    - name: Import stats.json
      run: |
        curl -O https://raw.githubusercontent.com/simonw/package-stats/main/stats.json
        python build_stats.py content.db stats.json
    - name: Build search index
      run: dogsheep-beta index dogsheep-index.db templates/dogsheep-beta.yml
    - name: Soundness check
      run: |
        datasette . --get "/"
        datasette . --get "/plugins"
        datasette . --get "/news"
        datasette . --get "/-/beta"
    - name: Set up Cloud Run
      uses: google-github-actions/setup-gcloud@master
      with:
        version: '275.0.0'
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: Deploy to Cloud Run
      run: |-
        gcloud config set run/region us-central1
        gcloud config set project datasette-222320
        datasette publish cloudrun content.db docs-index.db dogsheep-index.db \
          --service datasette-io \
          --template-dir=templates \
          --metadata=metadata.yml \
          --plugins-dir=plugins \
          --static=static:static \
          --install=datasette-render-markdown \
          --install=datasette-template-sql \
          --install=python-dateutil \
          --install=datasette-vega \
          --install=datasette-atom \
          --install=datasette-graphql \
          --install 'dogsheep-beta>=0.10'
